name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
        type: string
      changelog:
        description: 'Changelog for this release (Markdown supported)'
        required: true
        default: '- Fixed bug X\n- Added feature Y'
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ github.run_id }}
          path: build/libs/

  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Artifacts-${{ github.run_id }}
          path: release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*.jar
          tag_name: v${{ github.event.inputs.version }}
          name: "Release ${{ github.event.inputs.version }}"
          body: ${{ github.event.inputs.changelog }}
          prerelease: false

  modrinth:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Artifacts-${{ github.run_id }}
          path: ./artifacts

      - name: Find JAR file
        id: find-jar
        run: |
          JARFILE=$(find ./artifacts -maxdepth 1 -name "*.jar" -not -name "*-dev.jar" -not -name "*-sources.jar" | head -n 1)
          if [[ -z "$JARFILE" ]]; then
            echo "::error::No suitable JAR file found in ./artifacts"
            exit 1
          fi
          echo "Found JAR: $JARFILE"
          echo "jarfile=$JARFILE" >> $GITHUB_OUTPUT

      - name: Upload to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          files: ${{ steps.find-jar.outputs.jarfile }}
          name: "Release ${{ github.event.inputs.version }}"
          version: ${{ github.event.inputs.version }}
          changelog: ${{ github.event.inputs.changelog }}
          version-type: release
          loaders: fabric
          game-versions: 1.21.4