name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:

permissions:
  contents: write  # Gives GITHUB_TOKEN rights to create releases

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: release-files

      - name: Get current date
        id: date
        run: echo "date=$(date +'%d-%m-%Y_%H:%M')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*.jar
          tag_name: release-${{ env.date }}
          name: "Release ${{ env.date }}"
          body: "This release is fully automated. If you run into any issues, just file a bug report in Issues."